apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: sistema-noticias-statefulset
spec:
  replicas: 1
  templates:
    metadata:
      labels:
        app: sistema-noticias-statefulset
      nome: sistema-noticias    
    spec: 
      containers:
        - name: sistema-noticias-container
          image: aluracursos/sistema-noticias:1
          ports:  
            - containerPort: 80
          envFrom: 
            - confgMapRef:
              name: sistema-configmap
          volumeMounts:
            - name: imagens  
              monthPath: /home
            - name: sessao  
              monthPath:  /home
          livenessProbe:
            httpGet:
              path:   / 
              port: 80      
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds:  20

          readinessProbe:
            httpGet: 
              path:   /
              port: 80      
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 3  

      volumes:    
        - name: imagens
          PersistenctVolumeClaim:
            claimName: imagens-pvc
        - name: sessao
          PersistenctVolumeClaim:
            claimName: sessao-pvc
  selector: 
    matchLabels:
      app: sistema-noticias
  serviceName: svc-sistema-noticias                  